### ISSUE TITLE
oracdc not working with oracle online redo log files

### ISSUE THREAD

**Issue by ankitsingh95** [averemee-si/oracdc#12]
Hi Team,

As can I check oracdc is not working with the online redo.log file, It only works for the archive redo.log files due to this connector is not able to work on a real-time system(DB changes).

If any possibility or plan then kindly update .

Thanks,
Ankit

**Comment by averemee-si** [comment]
Hi Ankit,

Yes, we work only with archived redo logs and our customers/prospects uses oracdc connected to standby database for running LogMiner. Now we work on running oracdc with LogMiner running on any compatible Oracle instance. We think about online redo log processing.

Regards,
Aleksei

**Comment by ankitsingh95** [comment]
Thanks for  the quick update I hope very soon this feature available in  oracdc
