### ISSUE TITLE
convert number (38,4)

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#15]
Hi Aleksej,
I have issue with convert number NUMBER(38,4)

"POINTPAID" NUMBER(38,4) => "POINTPAID": "AA==" 

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Could you please take a look at [Some columns values are getting encrypted #11](https://github.com/averemee-si/oracdc/issues/11).

Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksej,
Thank you very much!
Regards,
Son
