### ISSUE TITLE
Increase Row fetch size for oracdc

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#19]
Hi Aleksei,
Can you increase row fetch size in JDBC please? (modify default)

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Parameter a2.fetch.size added (32 - default value)
Available together with other latest fixes features in [0.9.7.8 - MAY-21 features/fixes](https://github.com/averemee-si/oracdc/releases/tag/v0.9.7.8)

Best regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksei,
Wow, Thanh you and your team very much for your fixes.
Regards,
Son
