### ISSUE TITLE
oracle physical backup database in real time？

### ISSUE THREAD

**Issue by Gumiry** [averemee-si/oracdc#67]
Hello, 
  I have a requirement at present, that is, to synchronize the data of the oracle physical backup database in real time, do you support real-time synchronization of data from the database to the new database?
  Looking forward to hearing from you！

**Comment by Gumiry** [comment]
Hi averemee-si,

Thank you for your reply.

You know that OGG is a paid feature, I hope it is similar to flinkcdc synchronization, but flinkcdc does not support synchronization of oracle physical backup vaults, so I wonder if this synchronization software supports it?
Regards,
Gumiry

**Comment by averemee-si** [comment]
Hi Gumiry,

Unfortunately, **oracdc** supports CDC using physical standby, but only for archived (not standby!) redo log - for more information please see [How to config online redo logs processing on physical standby](https://github.com/averemee-si/oracdc/discussions/53)
We are currently working on a new version that will read Oracle redo log files directly without using LogMiner. We plan to release it in JAN-2025.

Feel free to contact me if you need more info on connector configuration for physical standby.

Regards,
Aleksei

**Comment by Gumiry** [comment]
Hi Aleksei,

Thank you for letting me know this.

Warmest Regards,
Gumiry
