### ISSUE TITLE
NCLOB data types supported yet!

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#7]
Hi Aleksej,

Could you please add more NCLOB data types?

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Added in [add NCLOB support](https://github.com/averemee-si/oracdc/releases/tag/v0.9.7.1)

Regards,
Aleksej

**Comment by sonnguyen-dba** [comment]
Thanks Aleksej,
Regards,
Son
